"""Assemble PROOF.md from the generated result files.

Nothing in PROOF.md is typed by hand. Every table is read out of `results/`, and any section
whose inputs are missing says so rather than quietly disappearing, so a gap in the evidence is
visible instead of silent.

    python scripts/evaluate.py --seeds 20 --out results/eval
    python scripts/eval_gate.py
    python scripts/benchmark_intel.py
    python scripts/make_proof.py
"""

from __future__ import annotations

import argparse
import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

NL = chr(10)

MISSING = (
    "_Not generated on this machine. Run the command above and re-run "
    "`python scripts/make_proof.py`._"
)


def _excerpt(path: Path, head: int = 18, tail: int = 14) -> str:
    """First and last lines of a captured run, so the middle can be long without hiding."""
    if not path.exists():
        return "(not captured on this machine)"
    lines = [ln.rstrip() for ln in path.read_text(encoding="utf-8").splitlines()]
    lines = [ln for ln in lines if ln.strip()]
    if len(lines) <= head + tail:
        return NL.join(lines)
    skipped = len(lines) - head - tail
    return NL.join(lines[:head] + [f"    ... {skipped} lines ..."] + lines[-tail:])


def read_md(path: Path, command: str) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8").strip()
    return f"> `{command}`\n\n{MISSING}"


def git_commit() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
            capture_output=True, text=True, timeout=10,
        )
        return out.stdout.strip() or "(not committed yet)"
    except Exception:
        return "(git unavailable)"


def host_line() -> str:
    try:
        from tandem.bench.ovutil import device_report

        rep = device_report()
        devs = rep.get("devices") or []
        if isinstance(devs, dict):
            devs = [{"device": k, **(v or {})} for k, v in devs.items()]
        names = ", ".join(
            f"`{d.get('device', '?')}` = "
            f"{(d.get('full_device_name') or d.get('full_name') or '?').strip()}"
            for d in devs
        ) or "none reported"
        validated = rep.get("intel_validated")
        caveat = rep.get("caveat") or ""
        return (
            f"- Host: `{platform.processor() or platform.machine()}`, {platform.system()} "
            f"{platform.release()}\n"
            f"- OpenVINO devices: {names}\n"
            f"- Intel-validated platform: **{validated}**"
            + (f" — {caveat}" if caveat else "")
        )
    except Exception as exc:  # the report is evidence, so say why it is absent
        return f"- Device report unavailable on this machine: `{exc}`"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=ROOT / "PROOF.md")
    args = ap.parse_args()

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    parts = [
        "# Proof",
        "",
        "Every table below is generated by `scripts/make_proof.py` from the files in "
        "`results/`. None of it is typed by hand, and a section with no data says so instead "
        "of being omitted.",
        "",
        f"Generated {stamp} · commit `{git_commit()}`",
        "",
        "## Machine these numbers came from",
        "",
        host_line(),
        "",
        "> ⚠️ **The development machine is not an Intel platform.** OpenVINO's CPU plugin runs "
        "on it and produces real IR, real INT8 quantization and real measurements, but Intel "
        "does not validate AMD hosts, and there is no Intel iGPU or NPU here to measure. "
        "`scripts/benchmark_intel.py` detects the host itself and prints this caveat with every "
        "run; on a Core Ultra it will enumerate CPU, GPU and NPU with no changes. Treat the "
        "latency table as evidence that the pipeline is genuinely quantized and genuinely "
        "running through OpenVINO, not as an Intel benchmark.",
        "",
        "---",
        "",
        "## 0. One command, end to end",
        "",
        "> `python scripts/voice_to_table.py --audio assets/audio/set_the_table.wav --seed 1`",
        "",
        "Live speech through Speechmatics, intent parsed locally by a 1.5B model in OpenVINO "
        "INT4, plan expanded against the scene, every step gated, both arms executing. The "
        "captured run below is `results/voice_episode_log.txt` verbatim; the full record, "
        "including every step result, is in `results/voice_episode.json`.",
        "",
        "```",
        _excerpt(ROOT / "results/voice_episode_log.txt"),
        "```",
        "",
        "---",
        "",
        "## 1. Safety gate",
        "",
        "> `python scripts/eval_gate.py`",
        "",
        read_md(ROOT / "results/gate/gate_scorecard.md", "python scripts/eval_gate.py"),
        "",
        "---",
        "",
        "## 2. Task, across randomized seeds",
        "",
        "> `python scripts/evaluate.py --seeds 20 --out results/eval`",
        "",
        read_md(
            ROOT / "results/eval/scorecard.md",
            "python scripts/evaluate.py --seeds 20 --out results/eval",
        ),
        "",
        "---",
        "",
        "## 3. OpenVINO devices, latency and throughput",
        "",
        "> `python scripts/benchmark_intel.py`",
        "",
    ]

    bench = sorted((ROOT / "results").glob("benchmark_*.md"))
    parts.append(
        read_md(ROOT / "results/openvino_latency.md", "python scripts/export_models.py")
        if (ROOT / "results/openvino_latency.md").exists()
        else (bench[0].read_text(encoding="utf-8").strip() if bench else MISSING)
    )

    parts += [
        "",
        "---",
        "",
        "## 4. Quantization vs task quality",
        "",
        read_md(ROOT / "results/openvino_accuracy.md", "python scripts/export_models.py"),
        "",
        "---",
        "",
        "## 5. Language planner",
        "",
        read_md(
            ROOT / "results/planner_scorecard.md",
            "python tandem/planner/benchmark.py --device CPU --both",
        ),
        "",
        "---",
        "",
        "## 5b. Closing the loop through the cameras",
        "",
        read_md(ROOT / "results/perception_loop.md",
                "python scripts/evaluate.py --seeds 6 --perception --out results/eval-perception"),
        "",
        "---",
        "",
        "## 6. Live speech",
        "",
        read_md(ROOT / "results/voice_scorecard.md",
                "python scripts/record_command.py --transcribe assets/audio/set_the_table.wav"),
        "",
        "---",
        "",
        "## 7. Distilled policy vs the scripted expert",
        "",
        read_md(ROOT / "results/policy_scorecard.md", "python scripts/eval_policy.py"),
        "",
        "---",
        "",
        "## What this does not show",
        "",
        "See [`MOCKS.md`](MOCKS.md) for the line between real and simulated, and "
        "[`CLAIMS.md`](CLAIMS.md) for every claim tagged by its evidence tier.",
        "",
    ]

    args.out.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {args.out.relative_to(ROOT)}")
    if update_readme():
        print("Wrote README.md results block")
    return 0


def update_readme() -> bool:
    """Fill the README's results block from the same files, so it cannot drift from PROOF.md."""
    readme = ROOT / "README.md"
    if not readme.exists():
        return False
    text = readme.read_text(encoding="utf-8")
    start, end = "<!-- RESULTS:START -->", "<!-- RESULTS:END -->"
    if start not in text or end not in text:
        return False

    lines: list[str] = []
    gate = ROOT / "results/gate/gate_scorecard.json"
    if gate.exists():
        g = json.loads(gate.read_text(encoding="utf-8"))
        lines.append(
            f"**Safety gate \u2014 {g['total']['passed']}/{g['total']['total']} cases.** "
            f"{g['refusals']['passed']}/{g['refusals']['total']} refused correctly, "
            f"{g['rewrites']['passed']}/{g['rewrites']['total']} repaired rather than refused, "
            f"{g['allows_negative_control']['passed']}/"
            f"{g['allows_negative_control']['total']} legitimate steps allowed through \u2014 the "
            f"negative control, without which the refusal score would mean nothing."
        )
    task = ROOT / "results/eval/scorecard.json"
    if task.exists():
        t = json.loads(task.read_text(encoding="utf-8"))
        n = t["config"]["n"]
        lines += [
            "",
            f"**Task \u2014 {n} randomized seeds, mean subgoal fraction "
            f"{t['subgoal_fraction']['mean']:.2f}.**",
            "",
            "| subgoal | rate |",
            "| --- | --- |",
        ]
        for k, v in t["subgoals"].items():
            lines.append(f"| {k} | {v['count']}/{n} ({v['rate']:.0%}) |")
        lines += [
            "",
            f"Hand-offs performed: `{t['handoff_modes']}`. Gate refusals raised during "
            f"execution: {t['gate_refusals']}. Re-plans: {t['replans']}.",
        ]
    if (ROOT / "results/openvino_accuracy.json").exists():
        lines += [
            "",
            "**Quantization.** Perception and the distilled policy are exported to OpenVINO IR "
            "in FP32, FP16 and NNCF INT8, with the accuracy cost of each measured on held-out "
            "seeds rather than assumed \u2014 see `PROOF.md` section 4.",
        ]
    if not lines:
        lines = ["_No results generated on this machine yet._"]

    head = text.split(start)[0]
    tail = text.split(end)[1]
    readme.write_text(
        head + start + "\n" + "\n".join(lines) + "\n" + end + tail, encoding="utf-8"
    )
    return True


if __name__ == "__main__":
    raise SystemExit(main())
