"""Assemble PROOF.md from the generated result files.

Nothing in PROOF.md is typed by hand. Every table is read out of `results/`, and any section
whose inputs are missing says so rather than quietly disappearing, so a gap in the evidence is
visible instead of silent.

    python scripts/evaluate.py --seeds 20 --out results/eval
    python scripts/eval_gate.py
    python scripts/benchmark_intel.py
    python scripts/make_proof.py
"""

from __future__ import annotations

import argparse
import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

MISSING = (
    "_Not generated on this machine. Run the command above and re-run "
    "`python scripts/make_proof.py`._"
)


def read_md(path: Path, command: str) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8").strip()
    return f"> `{command}`\n\n{MISSING}"


def git_commit() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
            capture_output=True, text=True, timeout=10,
        )
        return out.stdout.strip() or "(not committed yet)"
    except Exception:
        return "(git unavailable)"


def host_line() -> str:
    try:
        from tandem.bench.ovutil import device_report

        rep = device_report()
        devs = rep.get("devices") or []
        if isinstance(devs, dict):
            devs = [{"device": k, **(v or {})} for k, v in devs.items()]
        names = ", ".join(
            f"`{d.get('device', '?')}` = "
            f"{(d.get('full_device_name') or d.get('full_name') or '?').strip()}"
            for d in devs
        ) or "none reported"
        validated = rep.get("intel_validated")
        caveat = rep.get("caveat") or ""
        return (
            f"- Host: `{platform.processor() or platform.machine()}`, {platform.system()} "
            f"{platform.release()}\n"
            f"- OpenVINO devices: {names}\n"
            f"- Intel-validated platform: **{validated}**"
            + (f" — {caveat}" if caveat else "")
        )
    except Exception as exc:  # the report is evidence, so say why it is absent
        return f"- Device report unavailable on this machine: `{exc}`"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=ROOT / "PROOF.md")
    args = ap.parse_args()

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    parts = [
        "# Proof",
        "",
        "Every table below is generated by `scripts/make_proof.py` from the files in "
        "`results/`. None of it is typed by hand, and a section with no data says so instead "
        "of being omitted.",
        "",
        f"Generated {stamp} · commit `{git_commit()}`",
        "",
        "## Machine these numbers came from",
        "",
        host_line(),
        "",
        "> ⚠️ **The development machine is not an Intel platform.** OpenVINO's CPU plugin runs "
        "on it and produces real IR, real INT8 quantization and real measurements, but Intel "
        "does not validate AMD hosts, and there is no Intel iGPU or NPU here to measure. "
        "`scripts/benchmark_intel.py` detects the host itself and prints this caveat with every "
        "run; on a Core Ultra it will enumerate CPU, GPU and NPU with no changes. Treat the "
        "latency table as evidence that the pipeline is genuinely quantized and genuinely "
        "running through OpenVINO, not as an Intel benchmark.",
        "",
        "---",
        "",
        "## 1. Safety gate",
        "",
        "> `python scripts/eval_gate.py`",
        "",
        read_md(ROOT / "results/gate/gate_scorecard.md", "python scripts/eval_gate.py"),
        "",
        "---",
        "",
        "## 2. Task, across randomized seeds",
        "",
        "> `python scripts/evaluate.py --seeds 20 --out results/eval`",
        "",
        read_md(
            ROOT / "results/eval/scorecard.md",
            "python scripts/evaluate.py --seeds 20 --out results/eval",
        ),
        "",
        "---",
        "",
        "## 3. OpenVINO devices, latency and throughput",
        "",
        "> `python scripts/benchmark_intel.py`",
        "",
    ]

    bench = sorted((ROOT / "results").glob("benchmark_*.md"))
    parts.append(
        bench[0].read_text(encoding="utf-8").strip()
        if bench
        else MISSING
    )

    parts += [
        "",
        "---",
        "",
        "## 4. Language planner",
        "",
        "> `python tandem/planner/benchmark.py --device CPU --both`",
        "",
        read_md(
            ROOT / "results/planner/planner_scorecard.md",
            "python tandem/planner/benchmark.py --device CPU --both",
        ),
        "",
        "---",
        "",
        "## 5. Perception and distilled policy",
        "",
        "> `python scripts/eval_policy.py`",
        "",
        read_md(ROOT / "results/policy/policy_scorecard.md", "python scripts/eval_policy.py"),
        "",
        "---",
        "",
        "## What this does not show",
        "",
        "See [`MOCKS.md`](MOCKS.md) for the line between real and simulated, and "
        "[`CLAIMS.md`](CLAIMS.md) for every claim tagged by its evidence tier.",
        "",
    ]

    args.out.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {args.out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
